[package]
name = "SGLoader"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.14.0", features = ["tokio"]}
reqwest = {version = "0.13.1", features = ["json"]}
tokio = {version = "1.49.0", features = ["full"]}
uuid = { version = "1.20.0", features = ["v4"] }
